name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          arch: [arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      run: |
        mkdir build
        cd build
        cmake ..
        
    - name: Build project
      run: |
        cd build
        cmake --build .